# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True, max_length=500, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='English_Alternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_synonym', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='English_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_word', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spanish_Alternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spanish_synonym', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spanish_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spanish_word', models.CharField(max_length=100, unique=True)),
                ('spanish_definition', models.TextField(blank=True, max_length=1000, null=True)),
                ('english_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='child_spanish', to='glosario.English_Entry')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=100, unique=True)),
                ('parent_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_themes', to='glosario.Chapter')),
            ],
        ),
        migrations.AddField(
            model_name='spanish_alternative',
            name='spanish_original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spanish_alternatives', to='glosario.Spanish_Entry'),
        ),
        migrations.AddField(
            model_name='english_entry',
            name='parent_theme',
            field=models.ManyToManyField(related_name='child_entries', to='glosario.Theme'),
        ),
        migrations.AddField(
            model_name='english_alternative',
            name='english_original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='english_alternatives', to='glosario.English_Entry'),
        ),
        migrations.AddField(
            model_name='comment',
            name='english_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='glosario.English_Entry'),
        ),
    ]
