# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glosario', '0002_auto_20170630_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spanish_entry',
            name='spanish_included',
            field=models.ManyToManyField(blank=True, null=True, related_name='spanish_main', to='glosario.Spanish_Entry'),
        ),
    ]
