# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glosario', '0004_auto_20170724_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approved_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(default='engtranslator', max_length=100),
        ),
    ]
