# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-26 00:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('glosario', '0007_auto_20170925_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_favorite', models.BooleanField(default=True)),
                ('by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_mark_favorites', 'Can mark favorites'),),
            },
        ),
        migrations.AlterModelOptions(
            name='english_entry',
            options={'permissions': (('can_create_entry', 'Can create entry'), ('can_edit_entry', 'Can edit entry'), ('can_modify_users', 'Can modify users'))},
        ),
        migrations.AddField(
            model_name='favorite',
            name='english_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited', to='glosario.English_Entry'),
        ),
    ]
