# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glosario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='english_entry',
            name='english_related',
            field=models.ManyToManyField(blank=True, null=True, related_name='_english_entry_english_related_+', to='glosario.English_Entry'),
        ),
        migrations.AddField(
            model_name='spanish_entry',
            name='spanish_included',
            field=models.ManyToManyField(blank=True, null=True, related_name='_spanish_entry_spanish_included_+', to='glosario.Spanish_Entry'),
        ),
    ]
