# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glosario', '0003_auto_20170720_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(default='blank', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='english_alternative',
            name='english_synonym',
            field=models.CharField(default='vlank', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spanish_alternative',
            name='spanish_synonym',
            field=models.CharField(default='vlankk', max_length=100),
            preserve_default=False,
        ),
    ]
